import React, { useEffect, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Linking,
  Modal,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import LinearGradient from 'react-native-linear-gradient';
import AppIcon from '../components/AppIcon';
import { getBottomInset, getTopInset } from '../utils/layout';
import {
  API_BASE_URL,
  ApiError,
  certificatesService,
} from '../api';

type CertificateItem = {
  id: string;
  title: string;
  subtitle: string;
  code: string;
  recipientName: string;
  pdfUrl: string | null;
  downloadPath: string | null;
  issueDate: string;
  status: string;
  description: string;
  eventName: string;
  certificateNumber?: string;
};

type Props = {
  onBack: () => void;
  onNotifications?: () => void;
};

function mapCerts(list: any[]): CertificateItem[] {
  return list.map((c: any, i: number) => {
    const code = c.verificationCode || c.code || '';
    const pdfUrl = c.pdfUrl || null;
    return {
      id: c._id || String(i + 1),
      title: c.title || 'Certificate of Appreciation',
      subtitle: c.description || c.eventName || 'Official Recognition',
      code,
      certificateNumber: c.certificateNumber || '',
      recipientName: c.recipientName || '',
      pdfUrl,
      downloadPath:
        pdfUrl ||
        (code
          ? `${API_BASE_URL}/certificates/download-pdf/${code}`
          : null),
      issueDate: c.issueDate
        ? new Date(c.issueDate).toLocaleDateString('en-GB', {
            day: 'numeric',
            month: 'short',
            year: 'numeric',
          })
        : '—',
      status: String(c.status || 'ISSUED').toUpperCase(),
      description: c.description || '',
      eventName: c.eventName || '',
    };
  });
}

export default function UserCertificatesScreen({
  onBack,
  onNotifications,
}: Props) {
  const [certificates, setCertificates] = useState<CertificateItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedCert, setSelectedCert] = useState<CertificateItem | null>(null);

  const fetchCertificates = async () => {
    setLoading(true);
    setError('');
    try {
      const res: any = await certificatesService.listMine();
      const list = Array.isArray(res)
        ? res
        : Array.isArray(res?.items)
        ? res.items
        : Array.isArray(res?.data)
        ? res.data
        : [];
      setCertificates(mapCerts(list));
    } catch (err) {
      if (
        err instanceof ApiError &&
        (err.status === 401 ||
          err.message.toLowerCase().includes('authentication'))
      ) {
        setError(
          'Authentication required. Please log in to view your certificates.',
        );
      } else {
        setError(
          err instanceof ApiError
            ? err.message
            : 'Failed to load certificates.',
        );
      }
      setCertificates([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void fetchCertificates();
  }, []);

  const handleDownload = async (cert: CertificateItem) => {
    try {
      const targetUrl = cert.pdfUrl || cert.downloadPath;
      if (!targetUrl) {
        Alert.alert(
          'PDF Not Available',
          'The PDF file for this certificate has not been uploaded or generated by the Admin yet.',
        );
        return;
      }
      const url = targetUrl.startsWith('http')
        ? targetUrl
        : `${API_BASE_URL.replace('/api/v1', '')}${targetUrl.startsWith('/') ? '' : '/'}${targetUrl}`;
      await Linking.openURL(url);
    } catch {
      Alert.alert('Error', 'Could not open certificate download link.');
    }
  };

  const handleShare = async (cert: CertificateItem) => {
    try {
      const result: any = await certificatesService.shareWhatsapp(cert.id);
      if (result?.success === false) {
        throw new Error(result.error || 'WhatsApp share failed');
      }
      Alert.alert('Shared', 'Certificate details shared via WhatsApp.');
    } catch (error) {
      const text = encodeURIComponent(
        `🌱 *Paryavaran Prahri Certificate*\n\n` +
          `*${cert.title}*\n` +
          (cert.recipientName ? `Issued to: ${cert.recipientName}\n` : '') +
          (cert.certificateNumber ? `Cert No: ${cert.certificateNumber}\n` : '') +
          (cert.code ? `Verification Code: ${cert.code}\n` : '') +
          (cert.downloadPath
            ? `\nView/Verify Certificate:\n${
                cert.downloadPath.startsWith('http')
                  ? cert.downloadPath
                  : `${API_BASE_URL.replace('/api/v1', '')}${
                      cert.downloadPath.startsWith('/') ? '' : '/'
                    }${cert.downloadPath}`
              }`
            : ''),
      );
      try {
        await Linking.openURL(`https://wa.me/?text=${text}`);
      } catch {
        Alert.alert(
          'Share Failed',
          error instanceof ApiError
            ? error.message
            : 'Could not open WhatsApp for sharing.',
        );
      }
    }
  };

  return (
    <View style={styles.root}>
      {/* BACKGROUND GRADIENT */}
      <LinearGradient
        colors={['#e8faef', '#f4f9f4']}
        start={{ x: 0, y: 0 }}
        end={{ x: 0, y: 0.5 }}
        style={StyleSheet.absoluteFill}
      />

      {/* HEADER */}
      <View style={[styles.header, { paddingTop: getTopInset(16) }]}>
        <View style={styles.headerLeft}>
          <Pressable style={styles.backButton} onPress={onBack}>
            <AppIcon name="arrow-left" size={20} color="#111827" />
          </Pressable>
          <View>
            <Text style={styles.headerTitle}>My Certificates</Text>
            <Text style={styles.headerSubtitle}>
              Official Environmental Recognition
            </Text>
          </View>
        </View>
        {onNotifications ? (
          <Pressable style={styles.bellButton} onPress={onNotifications}>
            <AppIcon name="bell-outline" size={20} color="#111827" />
          </Pressable>
        ) : null}
      </View>

      {/* BODY / SCROLLVIEW */}
      <ScrollView
        contentContainerStyle={[
          styles.scrollContent,
          { paddingBottom: getBottomInset(24) },
        ]}
        showsVerticalScrollIndicator={false}>
        {loading ? (
          <View style={styles.loadingBox}>
            <ActivityIndicator size="large" color="#059669" />
            <Text style={styles.loadingText}>Loading certificates...</Text>
          </View>
        ) : error ? (
          <View style={styles.errorCard}>
            <AppIcon name="alert-circle-outline" size={32} color="#dc2626" />
            <Text style={styles.errorText}>{error}</Text>
            <Pressable style={styles.retryBtn} onPress={fetchCertificates}>
              <Text style={styles.retryBtnText}>Retry</Text>
            </Pressable>
          </View>
        ) : certificates.length === 0 ? (
          /* EMPTY STATE */
          <View style={styles.emptyCard}>
            <View style={styles.emptyIconBg}>
              <AppIcon name="ribbon-outline" size={36} color="#059669" />
            </View>
            <Text style={styles.emptyTitle}>No certificates available yet.</Text>
            <Text style={styles.emptySubtitle}>
              Certificates issued by Admin for your environmental contribution will appear here.
            </Text>
          </View>
        ) : (
          /* CERTIFICATE CARDS LIST */
          certificates.map(cert => (
            <View key={cert.id} style={styles.certCard}>
              {/* TOP ROW */}
              <View style={styles.certHeaderRow}>
                <View style={styles.certIconBg}>
                  <AppIcon name="award-outline" size={24} color="#d97706" />
                </View>
                <View style={styles.certTitleCol}>
                  <Text style={styles.certTitle}>{cert.title}</Text>
                  {cert.certificateNumber ? (
                    <Text style={styles.certNumber}>
                      No: {cert.certificateNumber}
                    </Text>
                  ) : cert.code ? (
                    <Text style={styles.certNumber}>Code: {cert.code}</Text>
                  ) : null}
                </View>
                <View
                  style={[
                    styles.statusBadge,
                    cert.status === 'REVOKED'
                      ? styles.statusRevoked
                      : styles.statusIssued,
                  ]}>
                  <Text
                    style={[
                      styles.statusText,
                      cert.status === 'REVOKED'
                        ? styles.statusRevokedText
                        : styles.statusIssuedText,
                    ]}>
                    {cert.status}
                  </Text>
                </View>
              </View>

              {/* DETAILS SECTION */}
              {cert.subtitle ? (
                <Text style={styles.certSubtitle}>{cert.subtitle}</Text>
              ) : null}

              <View style={styles.metaRow}>
                <View style={styles.metaItem}>
                  <AppIcon name="calendar-outline" size={14} color="#6b7280" />
                  <Text style={styles.metaText}>Issued: {cert.issueDate}</Text>
                </View>
                {cert.recipientName ? (
                  <View style={styles.metaItem}>
                    <AppIcon name="account-outline" size={14} color="#6b7280" />
                    <Text style={styles.metaText}>{cert.recipientName}</Text>
                  </View>
                ) : null}
              </View>

              {/* ACTION BUTTONS ROW */}
              <View style={styles.actionRow}>
                {/* VIEW BUTTON */}
                <Pressable
                  style={[styles.btn, styles.btnView]}
                  onPress={() => setSelectedCert(cert)}>
                  <AppIcon name="eye-outline" size={15} color="#1e40af" />
                  <Text style={[styles.btnText, { color: '#1e40af' }]}>View</Text>
                </Pressable>

                {/* DOWNLOAD BUTTON */}
                <Pressable
                  style={[styles.btn, styles.btnDownload]}
                  onPress={() => handleDownload(cert)}>
                  <AppIcon name="download-outline" size={15} color="#059669" />
                  <Text style={[styles.btnText, { color: '#059669' }]}>
                    Download
                  </Text>
                </Pressable>

                {/* SHARE BUTTON */}
                <Pressable
                  style={[styles.btn, styles.btnShare]}
                  onPress={() => handleShare(cert)}>
                  <AppIcon name="whatsapp" size={15} color="#15803d" />
                  <Text style={[styles.btnText, { color: '#15803d' }]}>
                    Share
                  </Text>
                </Pressable>
              </View>
            </View>
          ))
        )}
      </ScrollView>

      {/* VIEW CERTIFICATE MODAL */}
      {selectedCert ? (
        <Modal
          visible={Boolean(selectedCert)}
          transparent
          animationType="fade"
          onRequestClose={() => setSelectedCert(null)}>
          <View style={styles.modalOverlay}>
            <View style={styles.modalCard}>
              <View style={styles.modalHeader}>
                <View style={styles.modalHeaderLeft}>
                  <View style={styles.modalIconBg}>
                    <AppIcon name="ribbon" size={22} color="#d97706" />
                  </View>
                  <Text style={styles.modalHeaderTitle}>
                    Certificate Details
                  </Text>
                </View>
                <Pressable
                  style={styles.closeBtn}
                  onPress={() => setSelectedCert(null)}>
                  <AppIcon name="close" size={20} color="#6b7280" />
                </Pressable>
              </View>

              <ScrollView style={styles.modalBody}>
                <View style={styles.certPreviewBox}>
                  <Text style={styles.previewOrg}>PARAYAVARAN PRAHRI</Text>
                  <Text style={styles.previewTitle}>{selectedCert.title}</Text>
                  <Text style={styles.previewSub}>
                    This is proudly presented to
                  </Text>
                  <Text style={styles.previewRecipient}>
                    {selectedCert.recipientName || 'Valued Citizen'}
                  </Text>
                  {selectedCert.description ? (
                    <Text style={styles.previewDesc}>
                      {selectedCert.description}
                    </Text>
                  ) : null}
                  {selectedCert.eventName ? (
                    <Text style={styles.previewEvent}>
                      Event: {selectedCert.eventName}
                    </Text>
                  ) : null}

                  <View style={styles.previewFooterRow}>
                    <View>
                      <Text style={styles.previewFooterLabel}>Issued Date</Text>
                      <Text style={styles.previewFooterVal}>
                        {selectedCert.issueDate}
                      </Text>
                    </View>
                    {selectedCert.certificateNumber || selectedCert.code ? (
                      <View style={{ alignItems: 'flex-end' }}>
                        <Text style={styles.previewFooterLabel}>
                          Certificate No
                        </Text>
                        <Text style={styles.previewFooterVal}>
                          {selectedCert.certificateNumber || selectedCert.code}
                        </Text>
                      </View>
                    ) : null}
                  </View>
                </View>
              </ScrollView>

              <View style={styles.modalActionRow}>
                <Pressable
                  style={[styles.modalBtn, styles.btnDownload]}
                  onPress={() => {
                    const c = selectedCert;
                    setSelectedCert(null);
                    void handleDownload(c);
                  }}>
                  <AppIcon name="download-outline" size={16} color="#059669" />
                  <Text style={[styles.btnText, { color: '#059669' }]}>
                    Download
                  </Text>
                </Pressable>
                <Pressable
                  style={[styles.modalBtn, styles.btnShare]}
                  onPress={() => {
                    const c = selectedCert;
                    setSelectedCert(null);
                    void handleShare(c);
                  }}>
                  <AppIcon name="whatsapp" size={16} color="#15803d" />
                  <Text style={[styles.btnText, { color: '#15803d' }]}>
                    Share
                  </Text>
                </Pressable>
              </View>
            </View>
          </View>
        </Modal>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f4f9f4' },
  header: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eef2ef',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0a3617',
  },
  headerSubtitle: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  bellButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    padding: 16,
    gap: 14,
  },
  loadingBox: {
    padding: 40,
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    color: '#4b5563',
  },
  errorCard: {
    backgroundColor: '#fef2f2',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  errorText: {
    fontSize: 14,
    color: '#dc2626',
    textAlign: 'center',
  },
  retryBtn: {
    backgroundColor: '#dc2626',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  retryBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  emptyCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    marginTop: 20,
  },
  emptyIconBg: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#ecfdf5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#6b7280',
    textAlign: 'center',
    lineHeight: 19,
  },
  certCard: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    gap: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  certHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  certIconBg: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#fffbe6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#fef08a',
  },
  certTitleCol: {
    flex: 1,
  },
  certTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  certNumber: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusIssued: {
    backgroundColor: '#dcfce7',
  },
  statusRevoked: {
    backgroundColor: '#fee2e2',
  },
  statusText: {
    fontSize: 11,
    fontWeight: '700',
  },
  statusIssuedText: {
    color: '#15803d',
  },
  statusRevokedText: {
    color: '#b91c1c',
  },
  certSubtitle: {
    fontSize: 13,
    color: '#374151',
    lineHeight: 18,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    fontSize: 12,
    color: '#6b7280',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
  },
  btn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
  },
  btnView: {
    backgroundColor: '#eff6ff',
    borderColor: '#bfdbfe',
  },
  btnDownload: {
    backgroundColor: '#ecfdf5',
    borderColor: '#a7f3d0',
  },
  btnShare: {
    backgroundColor: '#f0fdf4',
    borderColor: '#bbf7d0',
  },
  btnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    maxHeight: '80%',
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  modalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  modalIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#fffbe6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalHeaderTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  closeBtn: {
    padding: 4,
  },
  modalBody: {
    padding: 16,
  },
  certPreviewBox: {
    backgroundColor: '#fcfdfa',
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: '#2b964f',
    alignItems: 'center',
    gap: 8,
  },
  previewOrg: {
    fontSize: 11,
    fontWeight: '800',
    color: '#059669',
    letterSpacing: 1.5,
  },
  previewTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0a3617',
    textAlign: 'center',
  },
  previewSub: {
    fontSize: 12,
    color: '#6b7280',
    fontStyle: 'italic',
  },
  previewRecipient: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  previewDesc: {
    fontSize: 12,
    color: '#374151',
    textAlign: 'center',
    lineHeight: 18,
    marginTop: 4,
  },
  previewEvent: {
    fontSize: 12,
    fontWeight: '600',
    color: '#059669',
  },
  previewFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  previewFooterLabel: {
    fontSize: 10,
    color: '#9ca3af',
  },
  previewFooterVal: {
    fontSize: 11,
    fontWeight: '700',
    color: '#374151',
  },
  modalActionRow: {
    flexDirection: 'row',
    padding: 16,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
  },
  modalBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
  },
});
